nomad_version: latest

nomad_bin_dir: /usr/local/bin
nomad_config_dir: /etc/nomad.d
nomad_data_dir: /var/lib/nomad
nomad_user: nomad
nomad_group: nomad

nomad_region: global
nomad_datacenter: dc1
nomad_bind_addr: 0.0.0.0
nomad_node_role: client
nomad_leave_on_interrupt: false
nomad_leave_on_terminate: false

nomad_servers_group_name: nomad_servers
nomad_servers: "{{ groups[nomad_servers_group_name] }}"
nomad_retry_join: "{{ nomad_servers }}"

nomad_port_http: 4646
nomad_port_rpc: 4647
nomad_port_serf: 4648

nomad_plugin_raw_exec_enabled: false
