---
- name: Setup Docker
  hosts: all
  become: true

  vars:
    docker_apt_arch: arm64
    pip_install_packages:
      - name: docker

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
