---
- name: Initial setup
  hosts: all
  become: true

  tasks:
    - name: Update & upgrade system
      apt:
        update_cache: true
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot host
      reboot:
      when: reboot_required_file.stat.exists
