---
- name: Setup Nomad
  hosts: nomad_servers
  become: true

  vars:
    nomad_region: local
    nomad_datacenter: home
    nomad_node_role: both
    nomad_plugin_raw_exec_enabled: true

  roles:
    - role: nomad
