consul_version: latest
consul_log_level: INFO

consul_bin_dir: /usr/local/bin
consul_config_dir: /etc/consul.d
consul_data_dir: /var/lib/consul
consul_user: consul
consul_group: consul

consul_datacenter: dc1
consul_bind_addr: "{{ ansible_default_ipv4.address | default(ansible_ip_addresses.0) }}"
consul_client_addr: "{{ '127.0.0.1' if consul_node_role == 'client' else '0.0.0.0' }}"
consul_node_role: client

consul_servers_group_name: consul_servers
consul_retry_join: "{{ groups[consul_servers_group_name] }}"

consul_port_http: 8500
consul_port_server: 8300
consul_port_dns: 8600
consul_port_serf_lan: 8301
consul_port_serf_wan: 8302

consul_ui_enabled: "{{ consul_node_role == 'server' }}"
consul_skip_leave_on_interrupt: "{{ consul_node_role == 'server' }}"
consul_leave_on_terminate: "{{ consul_node_role == 'client' }}"
